version: "3.9"
services:
  web:
    build: .
    args:
    - PORT=3000
    - ADDRESS=127.0.0.1
    depends_on:
      - database
    command: ./socialnetotus --port $PORT --address $ADDRESS
  database:
    image: mysql:5.7
    ports:
        - "3306:3306"
    command: --init-file poco_server.sql
    environment:
        MYSQL_ROOT_USER: root
        MYSQL_ROOT_PASSWORD: 1
    
