with recursive series as (
	select 1 as id union all
	select id + 1 as id
   from series
   where id < 100), 
   		cities as (select 'Santa Clara' city union all 
   		           select 'Los Angeles' union all 
   		           select 'Santa Clarita' union all 
   		           select 'San Bernardino' union all
   		           select 'Alameda' union all
   		           select 'San Mateo' union all 
   		           select 'Santa Barbara'   		           
   		          ),
   		first_names as (select 'John' first_name union all
   				select 'James' first_name union all
   				select 'David' first_name union all
   				select 'Jeremy' first_name union all
   				select 'Ron' first_name union all
   				select 'Katie' first_name union all
   				select 'Nikita' first_name union all
   				select 'Rachel' first_name union all
                select 'Aaron' first_name union all
                select 'Abbey' first_name union all
                select 'Abbie' first_name union all
                select 'Abby' first_name union all
                select 'Abdul' first_name union all
                select 'Abe' first_name union all
                select 'Abel' first_name union all
                select 'Abigail' first_name union all
                select 'Abraham' first_name union all
                select 'Abram' first_name union all
                select 'Ada' first_name union all
                select 'Adah' first_name union all
                select 'Adalberto' first_name union all
                select 'Adaline' first_name union all
                select 'Adam' first_name union all
                select 'Adan' first_name union all
                select 'Addie' first_name union all
                select 'Adela' first_name union all
                select 'Adelaida' first_name union all
                select 'Adelaide' first_name union all
                select 'Adele' first_name union all
                select 'Adelia' first_name union all
                select 'Adelina' first_name union all
                select 'Adeline' first_name union all
                select 'Adell' first_name union all
                select 'Adella' first_name union all
                select 'Adelle' first_name union all
                select 'Adena' first_name union all
                select 'Adina' first_name union all
                select 'Adolfo' first_name union all
                select 'Adolph' first_name union all
                select 'Adria' first_name union all
                select 'Adrian' first_name union all
                select 'Adriana' first_name union all
                select 'Adriane' first_name union all
                select 'Adrianna' first_name union all
                select 'Adrianne' first_name union all
                select 'Adrien' first_name union all
                select 'Adriene' first_name union all
                select 'Adrienne' first_name union all
                select 'Afton' first_name union all
                select 'Agatha' first_name union all
                select 'Agnes' first_name union all
                select 'Agnus' first_name union all
                select 'Agripina' first_name union all
                select 'Agueda' first_name union all
                select 'Agustin' first_name union all
                select 'Agustina' first_name union all
                select 'Ahmad' first_name union all
                select 'Ahmed' first_name union all
                select 'Ai' first_name union all
                select 'Aida' first_name union all
                select 'Aide' first_name union all
                select 'Aiko' first_name union all
                select 'Aileen' first_name union all
                select 'Ailene' first_name union all
                select 'Aimee' first_name union all
                select 'Aisha' first_name union all
                select 'Aja' first_name union all
                select 'Akiko' first_name union all
                select 'Akilah' first_name union all
                select 'Al' first_name union all
                select 'Alaina' first_name union all
                select 'Alaine' first_name union all
                select 'Alan' first_name union all
                select 'Alana' first_name union all
                select 'Alane' first_name union all
                select 'Alanna' first_name union all
                select 'Alayna' first_name union all
                select 'Alba' first_name union all
                select 'Albert' first_name union all
                select 'Alberta' first_name union all
                select 'Albertha' first_name union all
                select 'Albertina' first_name union all
                select 'Albertine' first_name union all
                select 'Alberto' first_name union all
                select 'Albina' first_name union all
                select 'Alda' first_name union all
                select 'Alden' first_name union all
                select 'Aldo' first_name union all
                select 'Alease' first_name union all
                select 'Alec' first_name union all
                select 'Alecia' first_name union all
                select 'Aleen' first_name union all
                select 'Aleida' first_name union all
                select 'Aleisha' first_name union all
                select 'Alejandra' first_name union all
                select 'Alejandrina' first_name union all
                select 'Alejandro' first_name union all
                select 'Alena' first_name union all
                select 'Alene' first_name union all
                select 'Alesha' first_name union all
                select 'Aleshia' first_name union all
                select 'Alesia' first_name union all
                select 'Alessandra' first_name union all
                select 'Aleta' first_name union all
                select 'Aletha' first_name union all
                select 'Alethea' first_name union all
                select 'Alethia' first_name union all
                select 'Alex' first_name union all
                select 'Alexa' first_name union all
                select 'Alexander' first_name union all
                select 'Alexandra' first_name union all
                select 'Alexandria' first_name union all
                select 'Alexia' first_name union all
                select 'Alexis' first_name union all
                select 'Alfonso' first_name union all
                select 'Alfonzo' first_name union all
                select 'Alfred' first_name union all
                select 'Alfreda' first_name union all
                select 'Alfredia' first_name union all
                select 'Alfredo' first_name union all
                select 'Ali' first_name union all
                select 'Alia' first_name union all
                select 'Alica' first_name union all
                select 'Alice' first_name union all
                select 'Alicia' first_name union all
                select 'Alida' first_name union all
                select 'Alina' first_name union all
                select 'Aline' first_name union all
                select 'Alisa' first_name union all
                select 'Alise' first_name union all
                select 'Alisha' first_name union all
                select 'Alishia' first_name union all
                select 'Alisia' first_name union all
                select 'Alison' first_name union all
                select 'Alissa' first_name union all
                select 'Alita' first_name union all
                select 'Alix' first_name union all
                select 'Aliza' first_name union all
                select 'Alla' first_name union all
                select 'Allan' first_name union all
                select 'Alleen' first_name union all
                select 'Allegra' first_name union all
                select 'Allen' first_name union all
                select 'Allena' first_name union all
                select 'Allene' first_name union all
                select 'Allie' first_name union all
                select 'Alline' first_name union all
                select 'Allison' first_name union all
                select 'Allyn' first_name union all
                select 'Allyson' first_name union all
                select 'Alma' first_name union all
                select 'Almeda' first_name union all
                select 'Almeta' first_name union all
                select 'Alona' first_name union all
                select 'Alonso' first_name union all
                select 'Alonzo' first_name union all
                select 'Alpha' first_name union all
                select 'Alphonse' first_name union all
                select 'Alphonso' first_name union all
                select 'Alta' first_name union all
                select 'Altagracia' first_name union all
                select 'Altha' first_name union all
                select 'Althea' first_name union all
                select 'Alton' first_name union all
                select 'Alva' first_name union all
                select 'Alvaro' first_name union all
                select 'Alvera' first_name union all
                select 'Alverta' first_name union all
                select 'Alvin' first_name union all
                select 'Alvina' first_name union all
                select 'Alyce' first_name union all
                select 'Alycia' first_name union all
                select 'Alysa' first_name union all
                select 'Alyse' first_name union all
                select 'Alysha' first_name union all
                select 'Alysia' first_name union all
                select 'Alyson' first_name union all
                select 'Alyssa' first_name union all
                select 'Amada' first_name union all
                select 'Amado' first_name union all
                select 'Amal' first_name union all
                select 'Amalia' first_name union all
                select 'Amanda' first_name union all
                select 'Amber' first_name union all
                select 'Amberly' first_name union all
                select 'Ambrose' first_name union all
                select 'Amee' first_name union all
                select 'Amelia' first_name union all
                select 'America' first_name union all
                select 'Ami' first_name union all
                select 'Amie' first_name union all
                select 'Amiee' first_name union all
                select 'Amina' first_name union all
                select 'Amira' first_name union all
                select 'Ammie' first_name union all
                select 'Amos' first_name union all
                select 'Amparo' first_name union all
                select 'Amy' first_name union all
                select 'An' first_name union all
                select 'Ana' first_name union all
                select 'Anabel' first_name union all
                select 'Analisa' first_name union all
                select 'Anamaria' first_name union all
                select 'Anastacia' first_name union all
                select 'Anastasia' first_name union all
                select 'Andera' first_name union all
                select 'Anderson' first_name union all
                select 'Andra' first_name union all
                select 'Andre' first_name union all
                select 'Andrea' first_name union all
                select 'Andreas' first_name union all
                select 'Andree' first_name union all
                select 'Andres' first_name union all
                select 'Andrew' first_name union all
                select 'Andria' first_name union all
                select 'Andy' first_name union all
                select 'Anette' first_name union all
                select 'Angel' first_name union all
                select 'Angela' first_name union all
                select 'Angele' first_name union all
                select 'Angelena' first_name union all
                select 'Angeles' first_name union all
                select 'Angelia' first_name union all
                select 'Angelic' first_name union all
                select 'Angelica' first_name union all
                select 'Angelika' first_name union all
                select 'Angelina' first_name union all
                select 'Angeline' first_name union all
                select 'Angelique' first_name union all
                select 'Angelita' first_name union all
                select 'Angella' first_name union all
                select 'Angelo' first_name union all
                select 'Angelyn' first_name union all
                select 'Angie' first_name union all
                select 'Angila' first_name union all
                select 'Angla' first_name union all
                select 'Angle' first_name union all
                select 'Anglea' first_name union all
                select 'Anh' first_name union all
                select 'Anibal' first_name union all
                select 'Anika' first_name union all
                select 'Anisa' first_name union all
                select 'Anisha' first_name union all
                select 'Anissa' first_name union all
                select 'Anita' first_name union all
                select 'Anitra' first_name union all
                select 'Anja' first_name union all
                select 'Anjanette' first_name union all
                select 'Anjelica' first_name union all
                select 'Ann' first_name union all
                select 'Anna' first_name union all
                select 'Annabel' first_name union all
                select 'Annabell' first_name union all
                select 'Annabelle' first_name union all
                select 'Annalee' first_name union all
                select 'Annalisa' first_name union all
                select 'Annamae' first_name union all
                select 'Annamaria' first_name union all
                select 'Annamarie' first_name union all
                select 'Anne' first_name union all
                select 'Anneliese' first_name union all
                select 'Annelle' first_name union all
                select 'Annemarie' first_name union all
                select 'Annett' first_name union all
                select 'Annetta' first_name union all
                select 'Annette' first_name union all
                select 'Annice' first_name union all
                select 'Annie' first_name union all
                select 'Annika' first_name union all
                select 'Annis' first_name union all
                select 'Annita' first_name union all
                select 'Annmarie' first_name union all
                select 'Anthony' first_name union all
                select 'Antione' first_name union all
                select 'Antionette' first_name union all
                select 'Antoine' first_name union all
                select 'Antoinette' first_name union all
                select 'Anton' first_name union all
                select 'Antone' first_name union all
                select 'Antonetta' first_name union all
                select 'Antonette' first_name union all
                select 'Antonia' first_name union all
                select 'Antonietta' first_name union all
                select 'Antonina' first_name union all
                select 'Antonio' first_name union all
                select 'Antony' first_name union all
                select 'Antwan' first_name union all
                select 'Anya' first_name union all
                select 'Apolonia' first_name union all
                select 'April' first_name union all
                select 'Apryl' first_name union all
                select 'Ara' first_name union all
                select 'Araceli' first_name union all
                select 'Aracelis' first_name union all
                select 'Aracely' first_name union all
                select 'Arcelia' first_name union all
                select 'Archie' first_name union all
                select 'Ardath' first_name union all
                select 'Ardelia' first_name union all
                select 'Ardell' first_name union all
                select 'Ardella' first_name union all
                select 'Ardelle' first_name union all
                select 'Arden' first_name union all
                select 'Ardis' first_name union all
                select 'Ardith' first_name union all
                select 'Aretha' first_name union all
                select 'Argelia' first_name union all
                select 'Argentina' first_name union all
                select 'Ariana' first_name union all
                select 'Ariane' first_name union all
                select 'Arianna' first_name union all
                select 'Arianne' first_name union all
                select 'Arica' first_name union all
                select 'Arie' first_name union all
                select 'Ariel' first_name union all
                select 'Arielle' first_name union all
                select 'Arla' first_name union all
                select 'Arlean' first_name union all
                select 'Arleen' first_name union all
                select 'Arlen' first_name union all
                select 'Arlena' first_name union all
                select 'Arlene' first_name union all
                select 'Arletha' first_name union all
                select 'Arletta' first_name union all
                select 'Arlette' first_name union all
                select 'Arlie' first_name union all
                select 'Arlinda' first_name union all
                select 'Arline' first_name union all
                select 'Arlyne' first_name union all
                select 'Armand' first_name union all
                select 'Armanda' first_name union all
                select 'Armandina' first_name union all
                select 'Armando' first_name union all
                select 'Armida' first_name union all
                select 'Arminda' first_name union all
                select 'Arnetta' first_name union all
                select 'Arnette' first_name union all
                select 'Arnita' first_name union all
                select 'Arnold' first_name union all
                select 'Arnoldo' first_name union all
                select 'Arnulfo' first_name union all
                select 'Aron' first_name union all
                select 'Arron' first_name union all
                select 'Art' first_name union all
                select 'Arthur' first_name union all
                select 'Artie' first_name union all
                select 'Arturo' first_name union all
                select 'Arvilla' first_name union all
                select 'Asa' first_name union all
                select 'Asha' first_name union all
                select 'Ashanti' first_name union all
                select 'Ashely' first_name union all
                select 'Ashlea' first_name union all
                select 'Ashlee' first_name union all
                select 'Ashleigh' first_name union all
                select 'Ashley' first_name union all
                select 'Ashli' first_name union all
                select 'Ashlie' first_name union all
                select 'Ashly' first_name union all
                select 'Ashlyn' first_name union all
                select 'Ashton' first_name union all
                select 'Asia' first_name union all
                select 'Asley' first_name union all
                select 'Assunta' first_name union all
                select 'Astrid' first_name union all
                select 'Asuncion' first_name union all
                select 'Athena' first_name union all
                select 'Aubrey' first_name union all
                select 'Audie' first_name union all
                select 'Audra' first_name union all
                select 'Audrea' first_name union all
                select 'Audrey' first_name union all
                select 'Audria' first_name union all
                select 'Audrie' first_name union all
                select 'Audry' first_name union all
                select 'August' first_name union all
                select 'Augusta' first_name union all
                select 'Augustina' first_name union all
                select 'Augustine' first_name union all
                select 'Augustus' first_name union all
                select 'Aundrea' first_name union all
                select 'Aura' first_name union all
                select 'Aurea' first_name union all
                select 'Aurelia' first_name union all
                select 'Aurelio' first_name union all
                select 'Aurora' first_name union all
                select 'Aurore' first_name union all
                select 'Austin' first_name union all
                select 'Autumn' first_name union all
                select 'Ava' first_name union all
                select 'Avelina' first_name union all
                select 'Avery' first_name union all
                select 'Avis' first_name union all
                select 'Avril' first_name union all
                select 'Awilda' first_name union all
                select 'Ayako' first_name union all
                select 'Ayana' first_name union all
                select 'Ayanna' first_name union all
                select 'Ayesha' first_name union all
                select 'Azalee' first_name union all
                select 'Azucena' first_name union all
                select 'Azzie' first_name union all
                select 'Babara' first_name union all
                select 'Babette' first_name union all
                select 'Bailey' first_name union all
                select 'Bambi' first_name union all
                select 'Bao' first_name union all
                select 'Barabara' first_name union all
                select 'Barb' first_name union all
                select 'Barbar' first_name union all
                select 'Barbara' first_name union all
                select 'Barbera' first_name union all
                select 'Barbie' first_name union all
                select 'Barbra' first_name union all
                select 'Bari' first_name union all
                select 'Barney' first_name union all
                select 'Barrett' first_name union all
                select 'Barrie' first_name union all
                select 'Barry' first_name union all
                select 'Bart' first_name union all
                select 'Barton' first_name union all
                select 'Basil' first_name union all
                select 'Basilia' first_name union all
                select 'Bea' first_name union all
                select 'Beata' first_name union all
                select 'Beatrice' first_name union all
                select 'Beatris' first_name union all
                select 'Beatriz' first_name union all
                select 'Beau' first_name union all
                select 'Beaulah' first_name union all
                select 'Bebe' first_name union all
                select 'Becki' first_name union all
                select 'Beckie' first_name union all
                select 'Becky' first_name union all
                select 'Bee' first_name union all
                select 'Belen' first_name union all
                select 'Belia' first_name union all
                select 'Belinda' first_name union all
                select 'Belkis' first_name union all
                select 'Bell' first_name union all
                select 'Bella' first_name union all
                select 'Belle' first_name union all
                select 'Belva' first_name union all
                select 'Ben' first_name union all
                select 'Benedict' first_name union all
                select 'Benita' first_name union all
                select 'Benito' first_name union all
                select 'Benjamin' first_name union all
                select 'Bennett' first_name union all
                select 'Bennie' first_name union all
                select 'Benny' first_name union all
                select 'Benton' first_name union all
                select 'Berenice' first_name union all
                select 'Berna' first_name union all
                select 'Bernadette' first_name union all
                select 'Bernadine' first_name union all
                select 'Bernard' first_name union all
                select 'Bernarda' first_name union all
                select 'Bernardina' first_name union all
                select 'Bernardine' first_name union all
                select 'Bernardo' first_name union all
                select 'Berneice' first_name union all
                select 'Bernetta' first_name union all
                select 'Bernice' first_name union all
                select 'Bernie' first_name union all
                select 'Berniece' first_name union all
                select 'Bernita' first_name union all
                select 'Berry' first_name union all
                select 'Bert' first_name union all
                select 'Berta' first_name union all
                select 'Bertha' first_name union all
                select 'Bertie' first_name union all
                select 'Bertram' first_name union all
                select 'Beryl' first_name union all
                select 'Bess' first_name union all
                select 'Bessie' first_name union all
                select 'Beth' first_name union all
                select 'Bethanie' first_name union all
                select 'Bethann' first_name union all
                select 'Bethany' first_name union all
                select 'Bethel' first_name union all
                select 'Betsey' first_name union all
                select 'Betsy' first_name union all
                select 'Bette' first_name union all
                select 'Bettie' first_name union all
                select 'Bettina' first_name union all
                select 'Betty' first_name union all
                select 'Bettyann' first_name union all
                select 'Bettye' first_name union all
                select 'Beula' first_name union all
                select 'Beulah' first_name union all
                select 'Bev' first_name union all
                select 'Beverlee' first_name union all
                select 'Beverley' first_name union all
                select 'Beverly' first_name union all
                select 'Bianca' first_name union all
                select 'Bibi' first_name union all
                select 'Bill' first_name union all
                select 'Billi' first_name union all
                select 'Billie' first_name union all
                select 'Billy' first_name union all
                select 'Billye' first_name union all
                select 'Birdie' first_name union all
                select 'Birgit' first_name union all
                select 'Blaine' first_name union all
                select 'Blair' first_name union all
                select 'Blake' first_name union all
                select 'Blanca' first_name union all
                select 'Blanch' first_name union all
                select 'Blanche' first_name union all
                select 'Blondell' first_name union all
                select 'Blossom' first_name union all
                select 'Blythe' first_name union all
                select 'Bo' first_name union all
                select 'Bob' first_name union all
                select 'Bobbi' first_name union all
                select 'Bobbie' first_name union all
                select 'Bobby' first_name union all
                select 'Bobbye' first_name union all
                select 'Bobette' first_name union all
                select 'Bok' first_name union all
                select 'Bong' first_name union all
                select 'Bonita' first_name union all
                select 'Bonnie' first_name union all
                select 'Bonny' first_name union all
                select 'Booker' first_name union all
                select 'Boris' first_name union all
                select 'Boyce' first_name union all
                select 'Boyd' first_name union all
                select 'Brad' first_name union all
                select 'Bradford' first_name union all
                select 'Bradley' first_name union all
                select 'Bradly' first_name union all
                select 'Brady' first_name union all
                select 'Brain' first_name union all
                select 'Branda' first_name union all
                select 'Brande' first_name union all
                select 'Brandee' first_name union all
                select 'Branden' first_name union all
                select 'Brandi' first_name union all
                select 'Brandie' first_name union all
                select 'Brandon' first_name union all
                select 'Brandy' first_name union all
                select 'Brant' first_name union all
                select 'Breana' first_name union all
                select 'Breann' first_name union all
                select 'Breanna' first_name union all
                select 'Breanne' first_name union all
                select 'Bree' first_name union all
                select 'Brenda' first_name union all
                select 'Brendan' first_name union all
                select 'Brendon' first_name union all
                select 'Brenna' first_name union all
                select 'Brent' first_name union all
                select 'Brenton' first_name union all
                select 'Bret' first_name union all
                select 'Brett' first_name union all
                select 'Brian' first_name union all
                select 'Briana' first_name union all
                select 'Brianna' first_name union all
                select 'Brianne' first_name union all
                select 'Brice' first_name union all
                select 'Bridget' first_name union all
                select 'Bridgett' first_name union all
                select 'Bridgette' first_name union all
                select 'Brigette' first_name union all
                select 'Brigid' first_name union all
                select 'Brigida' first_name union all
                select 'Brigitte' first_name union all
                select 'Brinda' first_name union all
                select 'Britany' first_name union all
                select 'Britney' first_name union all
                select 'Britni' first_name union all
                select 'Britt' first_name union all
                select 'Britta' first_name union all
                select 'Brittaney' first_name union all
                select 'Brittani' first_name union all
                select 'Brittanie' first_name union all
                select 'Brittany' first_name union all
                select 'Britteny' first_name union all
                select 'Brittney' first_name union all
                select 'Brittni' first_name union all
                select 'Brittny' first_name union all
                select 'Brock' first_name union all
                select 'Broderick' first_name union all
                select 'Bronwyn' first_name union all
                select 'Brook' first_name union all
                select 'Brooke' first_name union all
                select 'Brooks' first_name union all
                select 'Bruce' first_name union all
                select 'Bruna' first_name union all
                select 'Brunilda' first_name union all
                select 'Bruno' first_name union all
                select 'Bryan' first_name union all
                select 'Bryanna' first_name union all
                select 'Bryant' first_name union all
                select 'Bryce' first_name union all
                select 'Brynn' first_name union all
                select 'Bryon' first_name union all
                select 'Buck' first_name union all
                select 'Bud' first_name union all
                select 'Buddy' first_name union all
                select 'Buena' first_name union all
                select 'Buffy' first_name union all
                select 'Buford' first_name union all
                select 'Bula' first_name union all
                select 'Bulah' first_name union all
                select 'Bunny' first_name union all
                select 'Burl' first_name union all
                select 'Burma' first_name union all
                select 'Burt' first_name union all
                select 'Burton' first_name union all
                select 'Buster' first_name union all
                select 'Byron' first_name union all
                select 'Caitlin' first_name union all
                select 'Caitlyn' first_name union all
                select 'Calandra' first_name union all
                select 'Caleb' first_name union all
                select 'Calista' first_name union all
                select 'Callie' first_name union all
                select 'Calvin' first_name union all
                select 'Camelia' first_name union all
                select 'Camellia' first_name union all
                select 'Cameron' first_name union all
                select 'Cami' first_name union all
                select 'Camie' first_name union all
                select 'Camila' first_name union all
                select 'Camilla' first_name union all
                select 'Camille' first_name union all
                select 'Cammie' first_name union all
                select 'Cammy' first_name union all
                select 'Candace' first_name union all
                select 'Candance' first_name union all
                select 'Candelaria' first_name union all
                select 'Candi' first_name union all
                select 'Candice' first_name union all
                select 'Candida' first_name union all
                select 'Candie' first_name union all
                select 'Candis' first_name union all
                select 'Candra' first_name union all
                select 'Candy' first_name union all
                select 'Candyce' first_name union all
                select 'Caprice' first_name union all
                select 'Cara' first_name union all
                select 'Caren' first_name union all
                select 'Carey' first_name union all
                select 'Cari' first_name union all
                select 'Caridad' first_name union all
                select 'Carie' first_name union all
                select 'Carin' first_name union all
                select 'Carina' first_name union all
                select 'Carisa' first_name union all
                select 'Carissa' first_name union all
                select 'Carita' first_name union all
                select 'Carl' first_name union all
                select 'Carla' first_name union all
                select 'Carlee' first_name union all
                select 'Carleen' first_name union all
                select 'Carlena' first_name union all
                select 'Carlene' first_name union all
                select 'Carletta' first_name union all
                select 'Carley' first_name union all
                select 'Carli' first_name union all
                select 'Carlie' first_name union all
                select 'Carline' first_name union all
                select 'Carlita' first_name union all
                select 'Carlo' first_name union all
                select 'Carlos' first_name union all
                select 'Carlota' first_name union all
                select 'Carlotta' first_name union all
                select 'Carlton' first_name union all
                select 'Carly' first_name union all
                select 'Carlyn' first_name union all
                select 'Carma' first_name union all
                select 'Carman' first_name union all
                select 'Carmel' first_name union all
                select 'Carmela' first_name union all
                select 'Carmelia' first_name union all
                select 'Carmelina' first_name union all
                select 'Carmelita' first_name union all
                select 'Carmella' first_name union all
                select 'Carmelo' first_name union all
                select 'Carmen' first_name union all
                select 'Carmina' first_name union all
                select 'Carmine' first_name union all
                select 'Carmon' first_name union all
                select 'Carol' first_name union all
                select 'Carola' first_name union all
                select 'Carolann' first_name union all
                select 'Carole' first_name union all
                select 'Carolee' first_name union all
                select 'Carolin' first_name union all
                select 'Carolina' first_name union all
                select 'Caroline' first_name union all
                select 'Caroll' first_name union all
                select 'Carolyn' first_name union all
                select 'Carolyne' first_name union all
                select 'Carolynn' first_name union all
                select 'Caron' first_name union all
                select 'Caroyln' first_name union all
                select 'Carri' first_name union all
                select 'Carrie' first_name union all
                select 'Carrol' first_name union all
                select 'Carroll' first_name union all
                select 'Carry' first_name union all
                select 'Carson' first_name union all
                select 'Carter' first_name union all
                select 'Cary' first_name union all
                select 'Caryl' first_name union all
                select 'Carylon' first_name union all
                select 'Caryn' first_name union all
                select 'Casandra' first_name union all
                select 'Casey' first_name union all
                select 'Casie' first_name union all
                select 'Casimira' first_name union all
                select 'Cassandra' first_name union all
                select 'Cassaundra' first_name union all
                select 'Cassey' first_name union all
                select 'Cassi' first_name union all
                select 'Cassidy' first_name union all
                select 'Cassie' first_name union all
                select 'Cassondra' first_name union all
                select 'Cassy' first_name union all
                select 'Catalina' first_name union all
                select 'Catarina' first_name union all
                select 'Caterina' first_name union all
                select 'Catharine' first_name union all
                select 'Catherin' first_name union all
                select 'Catherina' first_name union all
                select 'Catherine' first_name union all
                select 'Cathern' first_name union all
                select 'Catheryn' first_name union all
                select 'Cathey' first_name union all
                select 'Cathi' first_name union all
                select 'Cathie' first_name union all
                select 'Cathleen' first_name union all
                select 'Cathrine' first_name union all
                select 'Cathryn' first_name union all
                select 'Cathy' first_name union all
                select 'Catina' first_name union all
                select 'Catrice' first_name union all
                select 'Catrina' first_name union all
                select 'Cayla' first_name union all
                select 'Cecelia' first_name union all
                select 'Cecil' first_name union all
                select 'Cecila' first_name union all
                select 'Cecile' first_name union all
                select 'Cecilia' first_name union all
                select 'Cecille' first_name union all
                select 'Cecily' first_name union all
                select 'Cedric' first_name union all
                select 'Cedrick' first_name union all
                select 'Celena' first_name union all
                select 'Celesta' first_name union all
                select 'Celeste' first_name union all
                select 'Celestina' first_name union all
                select 'Celestine' first_name union all
                select 'Celia' first_name union all
                select 'Celina' first_name union all
                select 'Celinda' first_name union all
                select 'Celine' first_name union all
                select 'Celsa' first_name union all
                select 'Ceola' first_name union all
                select 'Cesar' first_name union all
                select 'Chad' first_name union all
                select 'Chadwick' first_name union all
                select 'Chae' first_name union all
                select 'Chan' first_name union all
                select 'Chana' first_name union all
                select 'Chance' first_name union all
                select 'Chanda' first_name union all
                select 'Chandra' first_name union all
                select 'Chanel' first_name union all
                select 'Chanell' first_name union all
                select 'Chanelle' first_name union all
                select 'Chang' first_name union all
                select 'Chantal' first_name union all
                select 'Chantay' first_name union all
                select 'Chante' first_name union all
                select 'Chantel' first_name union all
                select 'Chantell' first_name union all
                select 'Chantelle' first_name union all
                select 'Chara' first_name union all
                select 'Charis' first_name union all
                select 'Charise' first_name union all
                select 'Charissa' first_name union all
                select 'Charisse' first_name union all
                select 'Charita' first_name union all
                select 'Charity' first_name union all
                select 'Charla' first_name union all
                select 'Charleen' first_name union all
                select 'Charlena' first_name union all
                select 'Charlene' first_name union all
                select 'Charles' first_name union all
                select 'Charlesetta' first_name union all
                select 'Charlette' first_name union all
                select 'Charley' first_name union all
                select 'Charlie' first_name union all
                select 'Charline' first_name union all
                select 'Charlott' first_name union all
                select 'Charlotte' first_name union all
                select 'Charlsie' first_name union all
                select 'Charlyn' first_name union all
                select 'Charmain' first_name union all
                select 'Charmaine' first_name union all
                select 'Charolette' first_name union all
                select 'Chas' first_name union all
                select 'Chase' first_name union all
                select 'Chasidy' first_name union all
                select 'Chasity' first_name union all
                select 'Chassidy' first_name union all
                select 'Chastity' first_name union all
                select 'Chau' first_name union all
                select 'Chauncey' first_name union all
                select 'Chaya' first_name union all
                select 'Chelsea' first_name union all
                select 'Chelsey' first_name union all
                select 'Chelsie' first_name union all
                select 'Cher' first_name union all
                select 'Chere' first_name union all
                select 'Cheree' first_name union all
                select 'Cherelle' first_name union all
                select 'Cheri' first_name union all
                select 'Cherie' first_name union all
                select 'Cherilyn' first_name union all
                select 'Cherise' first_name union all
                select 'Cherish' first_name union all
                select 'Cherly' first_name union all
                select 'Cherlyn' first_name union all
                select 'Cherri' first_name union all
                select 'Cherrie' first_name union all
                select 'Cherry' first_name union all
                select 'Cherryl' first_name union all
                select 'Chery' first_name union all
                select 'Cheryl' first_name union all
                select 'Cheryle' first_name union all
                select 'Cheryll' first_name union all
                select 'Chester' first_name union all
                select 'Chet' first_name union all
                select 'Cheyenne' first_name union all
                select 'Chi' first_name union all
                select 'Chia' first_name union all
                select 'Chieko' first_name union all
                select 'Chin' first_name union all
                select 'China' first_name union all
                select 'Ching' first_name union all
                select 'Chiquita' first_name union all
                select 'Chloe' first_name union all
                select 'Chong' first_name union all
                select 'Chris' first_name union all
                select 'Chrissy' first_name union all
                select 'Christa' first_name union all
                select 'Christal' first_name union all
                select 'Christeen' first_name union all
                select 'Christel' first_name union all
                select 'Christen' first_name union all
                select 'Christena' first_name union all
                select 'Christene' first_name union all
                select 'Christi' first_name union all
                select 'Christia' first_name union all
                select 'Christian' first_name union all
                select 'Christiana' first_name union all
                select 'Christiane' first_name union all
                select 'Christie' first_name union all
                select 'Christin' first_name union all
                select 'Christina' first_name union all
                select 'Christine' first_name union all
                select 'Christinia' first_name union all
                select 'Christoper' first_name union all
                select 'Christopher' first_name union all
                select 'Christy' first_name union all
                select 'Chrystal' first_name union all
                select 'Chu' first_name union all
                select 'Chuck' first_name union all
                select 'Chun' first_name union all
                select 'Chung' first_name union all
                select 'Ciara' first_name union all
                select 'Cicely' first_name union all
                select 'Ciera' first_name union all
                select 'Cierra' first_name union all
                select 'Cinda' first_name union all
                select 'Cinderella' first_name union all
                select 'Cindi' first_name union all
                select 'Cindie' first_name union all
                select 'Cindy' first_name union all
                select 'Cinthia' first_name union all
                select 'Cira' first_name union all
                select 'Clair' first_name union all
                select 'Claire' first_name union all
                select 'Clara' first_name union all
                select 'Clare' first_name union all
                select 'Clarence' first_name union all
                select 'Claretha' first_name union all
                select 'Claretta' first_name union all
                select 'Claribel' first_name union all
                select 'Clarice' first_name union all
                select 'Clarinda' first_name union all
                select 'Clarine' first_name union all
                select 'Claris' first_name union all
                select 'Clarisa' first_name union all
                select 'Clarissa' first_name union all
                select 'Clarita' first_name union all
                select 'Clark' first_name union all
                select 'Classie' first_name union all
                select 'Claud' first_name union all
                select 'Claude' first_name union all
                select 'Claudette' first_name union all
                select 'Claudia' first_name union all
                select 'Claudie' first_name union all
                select 'Claudine' first_name union all
                select 'Claudio' first_name union all
                select 'Clay' first_name union all
                select 'Clayton' first_name union all
                select 'Clelia' first_name union all
                select 'Clemencia' first_name union all
                select 'Clement' first_name union all
                select 'Clemente' first_name union all
                select 'Clementina' first_name union all
                select 'Clementine' first_name union all
                select 'Clemmie' first_name union all
                select 'Cleo' first_name union all
                select 'Cleopatra' first_name union all
                select 'Cleora' first_name union all
                select 'Cleotilde' first_name union all
                select 'Cleta' first_name union all
                select 'Cletus' first_name union all
                select 'Cleveland' first_name union all
                select 'Cliff' first_name union all
                select 'Clifford' first_name union all
                select 'Clifton' first_name union all
                select 'Clint' first_name union all
                select 'Clinton' first_name union all
                select 'Clora' first_name union all
                select 'Clorinda' first_name union all
                select 'Clotilde' first_name union all
                select 'Clyde' first_name union all
                select 'Codi' first_name union all
                select 'Cody' first_name union all
                select 'Colby' first_name union all
                select 'Cole' first_name union all
                select 'Coleen' first_name union all
                select 'Coleman' first_name union all
                select 'Colene' first_name union all
                select 'Coletta' first_name union all
                select 'Colette' first_name union all
                select 'Colin' first_name union all
                select 'Colleen' first_name union all
                select 'Collen' first_name union all
                select 'Collene' first_name union all
                select 'Collette' first_name union all
                select 'Collin' first_name union all
                select 'Colton' first_name union all
                select 'Columbus' first_name union all
                select 'Concepcion' first_name union all
                select 'Conception' first_name union all
                select 'Concetta' first_name union all
                select 'Concha' first_name union all
                select 'Conchita' first_name union all
                select 'Connie' first_name union all
                select 'Conrad' first_name union all
                select 'Constance' first_name union all
                select 'Consuela' first_name union all
                select 'Consuelo' first_name union all
                select 'Contessa' first_name union all
                select 'Cora' first_name union all
                select 'Coral' first_name union all
                select 'Coralee' first_name union all
                select 'Coralie' first_name union all
                select 'Corazon' first_name union all
                select 'Cordelia' first_name union all
                select 'Cordell' first_name union all
                select 'Cordia' first_name union all
                select 'Cordie' first_name union all
                select 'Coreen' first_name union all
                select 'Corene' first_name union all
                select 'Coretta' first_name union all
                select 'Corey' first_name union all
                select 'Cori' first_name union all
                select 'Corie' first_name union all
                select 'Corina' first_name union all
                select 'Corine' first_name union all
                select 'Corinna' first_name union all
                select 'Corinne' first_name union all
                select 'Corliss' first_name union all
                select 'Cornelia' first_name union all
                select 'Cornelius' first_name union all
                select 'Cornell' first_name union all
                select 'Corrie' first_name union all
                select 'Corrin' first_name union all
                select 'Corrina' first_name union all
                select 'Corrine' first_name union all
                select 'Corrinne' first_name union all
                select 'Cortez' first_name union all
                select 'Cortney' first_name union all
                select 'Cory' first_name union all
                select 'Courtney' first_name union all
                select 'Coy' first_name union all
                select 'Craig' first_name union all
                select 'Creola' first_name union all                
                select 'Tom' first_name	
   		),
   	 	last_names as (select 'Smith' last_name union all
			       select 'Johnson' last_name union all
   			       select 'Williams' last_name union all
   			       select 'Brown' last_name union all
   			       select 'Jones' last_name union all
   		               select 'Miller' last_name union all
   			       select 'Davis' last_name union all
   			       select 'Wilson' last_name union all
   			      select 'West' last_name	
   		)
select id, user_id, first_name, last_name
       dob, city, salary - mod(salary, 100) salary
from (select id, 
       substring(md5(rand()),1,20) user_id,
       (select first_name from first_names order by rand() limit 1) first_name,
       (select last_name from last_names order by rand() limit 1) last_name,
       date(concat_ws('-',(floor(1919+rand()*100)),
                          (floor(1+rand()*12)),
                          (floor(1+rand()*28))
                     )
           ) dob,
       (select city from cities order by rand() limit 1) city,
       floor((rand() * (120000 + 1)) + 35000) salary
from series) as t;